"""empty message

Revision ID: f3a252f4b71c
Revises: fb8d0a084b6b
Create Date: 2022-10-24 09:02:55.077376

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3a252f4b71c'
down_revision = 'fb8d0a084b6b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('eventId', sa.Integer(), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('dayStart', sa.Date(), nullable=False),
    sa.Column('dayEnd', sa.Date(), nullable=False),
    sa.Column('timeStart', sa.TIME(), nullable=False),
    sa.Column('timeEnd', sa.TIME(), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=45), nullable=False),
    sa.PrimaryKeyConstraint('eventId')
    )
    op.create_table('userName',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('firstName', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('lastName', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=45), nullable=False),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_table('member',
    sa.Column('memberId', sa.Integer(), nullable=False),
    sa.Column('event', sa.Integer(), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('power', mysql.VARCHAR(length=45), nullable=False),
    sa.ForeignKeyConstraint(['event'], ['event.eventId'], ),
    sa.ForeignKeyConstraint(['memberId'], ['userName.userId'], ),
    sa.PrimaryKeyConstraint('memberId')
    )
    op.create_table('users',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('firstName', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('lastName', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('userStatus', mysql.VARCHAR(length=45), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['userName.userId'], ),
    sa.PrimaryKeyConstraint('userId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('member')
    op.drop_table('userName')
    op.drop_table('event')
    # ### end Alembic commands ###
