"""empty message

Revision ID: fb8d0a084b6b
Revises: 87337cc6454b
Create Date: 2022-10-22 19:45:36.875904

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fb8d0a084b6b'
down_revision = '87337cc6454b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('firstName', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('lastName', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('userStatus', mysql.VARCHAR(length=45), nullable=True),
    sa.PrimaryKeyConstraint('userId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
